{"name": "test_duplicate_build_type", "status": "failed", "statusDetails": {"message": "AssertionError: User creation failed: Responding with error, status code: 400 (Bad Request).\n  Details: jetbrains.buildServer.server.rest.errors.BadRequestException: Cannot create user as user with the same username already exists, caused by: jetbrains.buildServer.users.DuplicateUserAccountException: The specified username 'user_1740481058' is already in use by some other user.\n  Invalid request. Please check the request URL and data are correct.\nassert 400 == 200\n +  where 400 = <Response [400]>.status_code", "trace": "self = <tests.test_build_config.TestBuildConfig object at 0x1031acfa0>\n\n    @allure.story(\"User cannot create duplicate Build Type IDs\")\n    @allure.description(\"User should not be able to create two build types with the same id\")\n    @pytest.mark.regression\n    @pytest.mark.negative\n    @pytest.mark.crud\n    def test_duplicate_build_type(self):\n        unique_time = int(time.time())\n        with allure.step(\"Create user\"):\n            user_response = self.create_user(f\"user_{unique_time}\", \"pass123\")\n>           assert user_response.status_code == 200, f\"User creation failed: {user_response.text}\"\nE           AssertionError: User creation failed: Responding with error, status code: 400 (Bad Request).\nE             Details: jetbrains.buildServer.server.rest.errors.BadRequestException: Cannot create user as user with the same username already exists, caused by: jetbrains.buildServer.users.DuplicateUserAccountException: The specified username 'user_1740481058' is already in use by some other user.\nE             Invalid request. Please check the request URL and data are correct.\nE           assert 400 == 200\nE            +  where 400 = <Response [400]>.status_code\n\ntests/test_build_config.py:51: AssertionError"}, "description": "User should not be able to create two build types with the same id", "steps": [{"name": "Create user", "status": "failed", "statusDetails": {"message": "AssertionError: User creation failed: Responding with error, status code: 400 (Bad Request).\n  Details: jetbrains.buildServer.server.rest.errors.BadRequestException: Cannot create user as user with the same username already exists, caused by: jetbrains.buildServer.users.DuplicateUserAccountException: The specified username 'user_1740481058' is already in use by some other user.\n  Invalid request. Please check the request URL and data are correct.\nassert 400 == 200\n +  where 400 = <Response [400]>.status_code\n", "trace": "  File \"/Users/mihailkulibaba/Desktop/work/side_task/wtf/M2_API/teamcity_api_tests/tests/test_build_config.py\", line 51, in test_duplicate_build_type\n    assert user_response.status_code == 200, f\"User creation failed: {user_response.text}\"\n"}, "start": 1740481058988, "stop": 1740481059008}], "start": 1740481058988, "stop": 1740481059008, "uuid": "57748fc3-fefb-47e7-8406-652ffe3932fa", "historyId": "ff7d084782513ce7dc3df607ceebce54", "testCaseId": "ff7d084782513ce7dc3df607ceebce54", "fullName": "tests.test_build_config.TestBuildConfig#test_duplicate_build_type", "labels": [{"name": "epic", "value": "Build Configuration"}, {"name": "feature", "value": "Create Build Type"}, {"name": "story", "value": "User cannot create duplicate Build Type IDs"}, {"name": "tag", "value": "crud"}, {"name": "tag", "value": "negative"}, {"name": "tag", "value": "regression"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_build_config"}, {"name": "subSuite", "value": "TestBuildConfig"}, {"name": "host", "value": "MacBook-Air-Mihail.local"}, {"name": "thread", "value": "72794-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_build_config"}]}